### ISSUE TITLE
Include a proof of inclusion in the header of every request resource in the x-proof-of-inclusion header

### ISSUE THREAD

**Issue by MichaelTaylor3D** [Datalayer-Storage/Distributed-Internet-Gateway#21]

**Comment by dkackman** [comment]
`chia.dotnet` endpoints added for v2.2.0 with the verify proof and get proof methods

https://www.nuget.org/packages/chia-dotnet/

**Comment by dkackman** [comment]
I think this one is done. closing. @MichaelTaylor3D reopen if needed
