### ISSUE TITLE
Create "sync to data layer" function

### ISSUE THREAD

**Issue by dkackman** [Datalayer-Storage/Distributed-Internet-Gateway#33]

**Comment by dkackman** [comment]
The sync to data layer function shall
- ensure that the dig node has a server coin for each DL subscription
- (optionally?) ensure that each subscription is mirrored

Conversely it shall
- remove any server coins for stores that are not subscribed in the DL

@MichaelTaylor3D - i am thinking of removing the current concept of sync which uses the mirrorlist from your infrastructure and replacing it with this definition of sync. I don't think that original concept applies anymore. If you disagree let's discuss here.

**Comment by MichaelTaylor3D** [comment]
lgtm

**Comment by dkackman** [comment]
https://github.com/Datalayer-Storage/Distributed-Internet-Gateway/pull/35
