### ISSUE TITLE
Add Healthcheck endpoint

### ISSUE THREAD

**Issue by MichaelTaylor3D** [Datalayer-Storage/Distributed-Internet-Gateway#62]

**Comment by dkackman** [comment]
how comprehensive do you want this to be? just web server up or check on chia connections, data layer file replication find-ability etc?

**Comment by dkackman** [comment]
https://github.com/Datalayer-Storage/Distributed-Internet-Gateway/commit/0c6088310ec29b631c3291198c8fea9e730b0a13
