### ISSUE TITLE
Create a CLI cmd to precache all the subscribed stores

### ISSUE THREAD

**Issue by MichaelTaylor3D** [Datalayer-Storage/Distributed-Internet-Gateway#68]

**Comment by dkackman** [comment]
precache:
- keys
- values
- Proof of Inclusion

anything else?

**Comment by MichaelTaylor3D** [comment]
1) well i think the filecache should be purged. When the node is offline, the roothashes can change and your cache will be out of date with no signal that its out of date. DIG should be always on. If you turn it off, then you have to rebuild the cache. Part Time DIG nodes wouldnt use the cache feature because of this.

2) we have to purge

3) Proof of inclusions are lazy cached, it would be nice to get them in precach to but i wasnt sure how hard that would hammer the RPC

4) yes im aware of this, thats why its a tricky issue. Im wondering if precache should only be involed manually.

5) added that to give the RPCS a break and allow other things to process"

Side note:
i wonder if we can figure out a way to READ directly from the database instead of going through the RPCs to keep from hammering the RPCs to hard. When we are just doing key lookups

here is a screenshot from the node table



![Image](https://github.com/Datalayer-Storage/Distributed-Internet-Gateway/assets/5665004/64cc5572-e6a1-46cb-ba6e-d03c321fc233)

**Comment by dkackman** [comment]
> 1. well i think the filecache should be purged. When the node is offline, the roothashes can change and your cache will be out of date with no signal that its out of date. DIG should be always on. If you turn it off, then you have to rebuild the cache. Part Time DIG nodes wouldnt use the cache feature because of this.

what if, on server start, it kicks off a background task to goes through the pre-cache and check the roothashes? A lot of stores will be very close to immutable (thinking NFT collections).

> 
>     2. we have to purge

I don't wanna! bwaaaa

> 
>     3. Proof of inclusions are lazy cached, it would be nice to get them in precach to but i wasnt sure how hard that would hammer the RPC
> 
>     4. yes im aware of this, thats why its a tricky issue. Im wondering if precache should only be involed manually.

At least for the initial cache action I agree.

> 
>     5. added that to give the RPCS a break and allow other things to process"
> 
> 
> Side note: i wonder if we can figure out a way to READ directly from the database instead of going through the RPCs to keep from hammering the RPCs to hard. When we are just doing key lookups

I'm not too worried about the RPCs. The database is the choke point anyways and I want to keep the RPC boundary between dig and chia.

> 
> here is a screenshot from the node table
> 
> ![Image](https://private-user-images.githubusercontent.com/5665004/311326070-64cc5572-e6a1-46cb-ba6e-d03c321fc233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjI3MTAsIm5iZiI6MTcwOTkyMjQxMCwicGF0aCI6Ii81NjY1MDA0LzMxMTMyNjA3MC02NGNjNTU3Mi1lNmExLTQ2Y2ItYmE2ZS1kMDNjMzIxZmMyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTgyNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU2NTQ2ODdlODRkM2RiYWZmOGRmZWQ4ZDcyNDViZTQyNWEzZTg5YjVlNzZiYmMyNTEyMzEwYzY0MjUxYzc3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4p-II2t_iOxM7c3F0UxZ7SdR1Q-5J7eZoT0i7GJoplc)

**Comment by MichaelTaylor3D** [comment]
Thwe roothashes are imutable, but the precache is "the latest key values" it doesnt care about roothash.
So if the roothash changes it means we cant trust the "latest value cache" 

Yes we can go in and check if they are still valid, but your not saving any processing, your still processing the keys one by one, so you might as well just rebuilt the cache from scratch right?

**Comment by MichaelTaylor3D** [comment]
Im exploring an idea wher we make a shortlived replica of the DB just for the prupose of precache. If we can pull this off, then we can precache in parallel without hitting RPC issues.

Alternatively, if we can build a seperate client just for READS, we have additional tools for faster data retrieval.

**Comment by dkackman** [comment]
> Im exploring an idea wher we make a shortlived replica of the DB just for the prupose of precache. If we can pull this off, then we can precache in parallel without hitting RPC issues.
> 
> Alternatively, if we can build a seperate client just for READS, we have additional tools for faster data retrieval. 

But can't we cache the latest root hash and check that?

**Comment by dkackman** [comment]
closed by https://github.com/Datalayer-Storage/Distributed-Internet-Gateway/pull/76
